algo = input("Digite algo: ")

print(f"Tipo: {type(algo)}")
print(f"É um número? {algo.isnumeric()}")
print(f"É alfa? {algo.isalpha()}")
print(f"É alfanumérico? {algo.isalnum()}")
print(f"É total maiúsculo? {algo.isupper()}")
print(f"É total minúscolo? {algo.islower()}")
print(f"É capitalizado? {algo.istitle()}")
print(f"É decimal? {algo.isdecimal()}")
print(f"É apenas digitos numéricos? {algo.isdigit()}")
print(f"É somente espaço? {algo.isspace()}")
print(f"Faz parte da tabela ASCII? {algo.isascii()}")
print(f"É printável? {algo.isprintable()}")
print(f"É um identificador? {algo.isidentifier()}")